set(DETECTITEASY_SOURCES true)

if (DEFINED X_RESOURCES)
    install(DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/db/" DESTINATION "${X_RESOURCES}/db")
    install(DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/db_extra/" DESTINATION "${X_RESOURCES}/db" OPTIONAL)
    install (DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/db_custom DESTINATION ${X_RESOURCES} OPTIONAL)
endif()
